baseURL : https://diplomantky.cz
languageCode : cz
title : Diplomantky.cz
publishDir : ./docs
DefaultContentLanguage: cz
languages:
  cz:
    languageName: Česky
    weight: 1
  en:
    languageName: English
    weight: 2